visjs/vis-network

examples/network/data/dotLanguage/dotEdgeStyles.html, examples/network/data/dotLanguage/dotPlayground.html
Githup is all https causing mixed content from CDN's to fail loading with the below message. All CDN URL's used in examples should be changed to https.
Blocked loading mixed active content “http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js”
=> Change script CDN URL's to https

examples/index.html
adds missing dot language examples to the example overview
=> chore(examples): add dot language examples to overview

lib/network/modules/components/Edge.js, test/Network.test.js
This is an original contribution from @channeladam: https://github.com/visjs-community/visjs-network/pull/43
> Fixes [visjs-network#42](https://github.com/visjs-community/visjs-network/issues/42)
> Automated tests updated to prove the solution.
partially fixes #7
=> visjs-network#43: Edge labels disappear when cluster is opened

docs/network/interaction.html, examples/network/exampleApplications/neighbourhoodHighlight.html, lib/network/modules/CanvasRenderer.js, lib/network/modules/InteractionHandler.js, lib/network/options.js
This pull request was originally by @micahstubbs
https://github.com/almende/vis/pull/4042
partially fixes #7 
---
This PR adds a new network interaction option to hide edges on zoom, hideEdgesOnZoom
This new option is patterned after the existing hideEdgesOnDrag option.
fix https://github.com/almende/vis/issues/4039
- `cd vis`
- run a local server on port `8080`
- visit the **Dynamic Data - Neighbourhood Highlight** example at  http://localhost:8080/examples/network/exampleApplications/neighbourhoodHighlight.html
- scroll to zoom
- notice that edges are not shown during zooming, and are shown again when zooming ends ✨
=> vis#4042: Hide edges on zoom v2

examples/network/data/dotLanguage/dotEdgeStyles.html, lib/network/dotparser.js
This is an original contribution from @geminoa: https://github.com/almende/vis/pull/3888
This was also copies to visjs-netwoek: https://github.com/visjs-community/visjs-network/pull/23
> This update is for fixing TODO for 'dir' support. It is to comply with behaviour of graphviz described in https://www.graphviz.org/doc/info/attrs.html#h:undir_note
Should be merged after #18. Than it is easier to test it.
partially fixes #7
=> vis#3888: add dir support for dot language

lib/network/modules/InteractionHandler.js
This is an original contribution from @Gelio: https://github.com/almende/vis/pull/4026
This was also copies to visjs-netwoek: 
https://github.com/visjs-community/visjs-network/pull/26
partially fixes #7
---
When supplying an edge tooltip (`title`) without providing a node tooltip (`title`), the edge's tooltip will be displayed even though the node is hovered and the tooltip is in the background.
This PR fixes that behavior.
---
How to reproduce:
Take a look at https://almende.github.io/vis/examples/network/data/scalingNodesEdgesLabels.html
- Hover over an edge until the tooltip appears
- Move the mouse towards a node (following the edge)
- Move the mouse into the node (following the edge)
The tooltip does not disappear, even though the edge is technically not visible now since the node is …
=> vis#4026: remove edge tooltip when hovering a node

lib/network/modules/SelectionHandler.js
This is an original contribution from @Gelio: https://github.com/almende/vis/pull/4027
This was also copies to visjs-netwoek: 
https://github.com/visjs-community/visjs-network/pull/29
this is an addition to #21
partially fixes #7
---
When the mouse enters a node while hovering over an edge previously, the node hover event is not emitted.
Here are the screenshots of this unintended behavior. I have marked the mouse position with a black dot.
This PR fixes that issue. It has been also mentioned in https://github.com/almende/vis/issues/3907, which this PR also fixes.
---
=> vis#4027: fix hover detection over nodes after hovering over an edge

docs/network/index.html, examples/network/events/interactionEvents.html, lib/network/modules/ManipulationSystem.js, lib/network/modules/SelectionHandler.js
This is an original contribution from @vasa93: https://github.com/almende/vis/pull/3771
This was also copies to visjs-network: 
https://github.com/visjs-community/visjs-network/pull/34
partially fixes #7
---
We need notification on control node dragging and drag end for Vis **Network**. We need this so we can introduce some constraints for connecting nodes, and we need to do that proactively by changing cursor to 'not-allowed' when connecting is not allowed.
To solve this we introduced two new events 'controlNodeDragging' and 'controlNodeDragEnd', that notify us about control node state. These events are generated inside _dragControlNode and _finishConnect functions respectively. With this implemented, we can now change cursor over control node by checking constraints at the moment when …
=> vis#3771: add new events to control drag and drop of nodes

lib/network/modules/components/shared/Label.js, lib/network/modules/components/shared/LabelSplitter.js, test/Label.test.js, test/network/textMeasurementOnHoverTest.html
This is an original contribution from @channeladam: https://github.com/visjs-community/visjs-network/pull/47
fixes https://github.com/visjs-community/visjs-network/issues/46
partially fixes #7
---
> See manual test html file /test/network/textMeasurementOnHoverTest.html
=> visjs-network#47: fix label measurement

examples/network/tests/hidden_edge_test.html, lib/network/modules/components/Edge.js, test/hidden_edge_test.html
This is an original contribution from @DarylMcCullough: https://github.com/visjs-community/visjs-network/pull/68
part of #7
---
Fixes issue #67 "Network - does updating an edge cause it to reset automatically in Hierarchical view".
There is an example of the buggy behavior in test/hidden_edge_test.html. To see the bug:
Click on node 3.
Drag it to the right.
Release the mouse.
Then hover over node 3 (or any other node or edge).
The graph will reset (it shouldn't).
The only change is to the file Edge.js in lib/network/modules/components. Rebuild using "yarn" and "yarn build" and then retry the example hidden_edge_test.html
=> visjs-network#68: hidden edge bug

lib/network/modules/components/shared/Label.js, test/Label.test.js
This is an original contribution from @channeladam: https://github.com/visjs-community/visjs-network/pull/45
fixes https://github.com/visjs-community/visjs-network/issues/44
part of #7
=> visjs-network#45: correctly set invalid labels to undefined

lib/network/options.js
This is an original contribution from @geminoa: https://github.com/visjs-community/visjs-network/pull/40
this is an addition to https://github.com/almende/vis/pull/3657 that is already merge here.
part of #7
=> visjs-network#40: fix type of zoomSpeed

examples/network/data/dotLanguage/dotEdgeStyles.html, lib/network/dotparser.js
This is an original contribution from @geminoa: https://github.com/visjs-community/visjs-network/pull/39
part of #7
---
> This series of patches is for adding 'penwidth' attribute for dot parser which defines the line width as described in https://www.graphviz.org/doc/info/attrs.html#d:penwidth. It includes refactoring of parseAttributeList() for reducing the number of lines to avoid max-statements limitation of lint.
=> visjs-network#39: add penwidth support for dot language

lib/network/modules/View.js
Coerce to number and throw if it isn't grater than zero.
Fixes #12.
All MWE from the issue either work correctly or throw right away.
=> fix: ensure that invalid scale is not passed to moveTo

.eslintrc.js
I thought it would be nice to prevent methods, attributes, etc. from being mixed but it fails when there are abstract methods. It's not particularly necessary anyway.
=> style(eslint): disable member-ordering

test/node-shapes.test.ts
|            | Before               | After                |
| ---------- | -------------------- | -------------------- |
| Passing    | 256                  | 504                  |
| Statements | 46.77% ( 3974/8497 ) | 48.22% ( 4097/8497 ) |
| Branches   | 41.27% ( 1695/4107 ) | 42.66% ( 1752/4107 ) |
| Functions  | 43.65% (  481/1102 ) | 47.19% (  520/1102 ) |
| Lines      | 47.23% ( 3814/8076 ) | 48.75% ( 3937/8076 ) |
=> test(node-shapes): add some node shapes tests

docs/network/nodes.html
It used to imply that FontAwesome and Ionicons are the only faces that
can be used. In reality these can only be used if the user ships them
themselves and others can be used too if loaded on the page.
Resolves #59.
=> chore(docs): correct nodes.icon.face description

README.md
The npm badge should link to the releases
=> chore: update npm badge

lib/shared/Activator.css, lib/shared/Activator.js
There was a mismatch between the class of the element (.vis-overlay) and the CSS (.vis .overlay) leading to the overlay not being properly positioned. Also the stopPropagation method doesn't seem to exist (anymore?) but is present on srcEvent so this is used instead.
Closes #121.
=> fix(click-to-use): fix errors and styling

docs/network/nodes.html, examples/network/nodeStyles/icons.html, lib/network/modules/components/nodes/shapes/Icon.js, lib/network/options.js, types/network/Network.d.ts
This solves issues with Font Awesome 5 which doesn't work unless the weight is bold. Size difference is used to indicate selected status if weight is forced.
Closes #139.
=> feat(node): add force weight option

package.json, scripts/examples-index/generate.ts, scripts/examples-index/index.template.html
The title was hardcoded to Vis Network Examples. Now it's reusable across packages.
=> chore(examples): make index page title configurable

.github/ISSUE_TEMPLATE.md
There were links pointing to the legacy Vis.js project. Also this no longer contains anything else but Network so mentioning a component is not necessary anymore.
=> chore(github): update issue template

docs/network/layout.html, examples/network/layout/hierarchicalLayoutMethods.html, lib/network/modules/LayoutEngine.js, lib/network/modules/layout-engine/index.ts, lib/network/options.js
This allows users to shake the nodes towards the leaves (default as it
was this way already) or the roots (this was the way it worked back when
the layout was broken) of the hierarchy if they so choose.
Closes #176.
=> feat(hierarchical-layout): add shake towards option

docs/network/edges.html, examples/network/edgeStyles/imageArrowHeads.html, lib/network/modules/EdgesHandler.js, lib/network/modules/components/Edge.js, lib/network/modules/components/edges/util/edge-base.ts, lib/network/modules/components/edges/util/end-points.ts, lib/network/modules/components/edges/util/types.ts, lib/network/options.js
Adds image arrow heads in similar fashion to image nodes.
Working example: http://jsfiddle.net/thomaash/67xaky4s/.
Todo:
Closes #153.
=> Image arrow heads

examples/network/edgeStyles/imageArrowHeads.html, examples/network/layout/hierarchicalLayoutOverlapAvoidance.html
Some paths in the examples pointed to nonexistent files. This fixes that.
=> chore(examples): fix broken script paths

.circleci/config.yml
This should finally close #183 for good.
It uses the files property from package.json to ensure that we have a single source of truth listing all the dist files that should be published on both npm and GitHub Pages.
=> ci: publish all the files from package.json/files

package-lock.json, package.json
This was introduced to bundle d.ts files. However it was never used
because it's not reliable. Sometimes the bundled files even contain
syntax errors.
Closes #221.
=> chore(package): remove unused dependency

examples/network/basic_usage/legacy.html, rollup.config.js
We added image inlining but the legacy build was never updated so the
nonstandard inline function ended up in the CSS pointing to some weird
nonexistent location causing all the buttons to appear transparent. They
worked just fine though you just couldn't see them unless you howered
them and a glow appeared around the empty void.
Closes #217.
=> fix(build): fix the legacy CSS

docs/network/index.html
There was an error in this which used the legacy property name as a name of the export (legacy: `vis.network.convertDOTNetwork`, new: `vis.parseDOTNetwork`, docs: `vis.convertDOTNetwork`).
Also the text was rewritten to clarify it's meaning as the original formulation was quite ambitious.
Closes #214.
=> docs(DOT): fix an error and clarify

dev-lib/bundle-css.d.ts, dev-lib/bundle-esm-index.d.ts, dev-lib/bundle-vis-network-index.d.ts, rollup.build.js
This allows more visually appealing imports when used with bundlers:
```typescript
// Old, but still works:
import * as vis from "vis-network/standalone/esm/vis-network";
// New, achieving the same result (ESM):
import * as vis from "vis-network/standalone";
// ESM explicitly:
import * as vis from "vis-network/standalone/esm";
// UMD explicitly:
import * as vis from "vis-network/standalone/umd";
```
This partially works in HTML but the old way is preferred (less requests,
library name in dev tools and better compatibility):
```html
<script
type="text/javascript"
src="https://unpkg.com/vis-network/standalone/umd/vis-network.min.js"
></script>
<script
type="module"
src="https://unpkg.com/vis-network/standalone/esm"
></script>
<script
type="text/javascript" …
```
=> feat(build): add index files to bundles

examples/network/edgeStyles/arrowAlignment.html
This demostrates #229. The arrows are visibly misaligned when the self reference circle is bigger than default. They are misaligned all the time actually but it's not really visible with smaller circumference.
=> example(arrow-alignment): add self ref alignment

lib/network/modules/EdgesHandler.js, lib/network/modules/ManipulationSystem.js, lib/network/modules/NodesHandler.js
Formerly DataSet._data was accessed directly. No idea how that could ever work at all. Now the proper methods from the API are used so there should be no further issues.
Closes #228.
=> fix(data-set): do not use private props

lib/network/modules/EdgesHandler.js
Data set docs: `Item | null`.
Data set implementation today: `Item | null`.
Data set implementation 5 years ago: `Item | null`.
EdgesHandler.js for the past 5 years:
```javascript
if (item !== undefined) {
item[prop]
}
```
I have no idea why no one noticed this for five years. It either got the
item from the data set or accessed a property on null and crashed.
PS: This has been introduced by a commit saying "updated docs".
=> fix(edges-handler): do not access props on null

examples/network/layout/hierarchicalLayoutMethods.html, lib/network/modules/LayoutEngine.js, lib/network/modules/layout-engine/index.ts
The layout originally made space for invisible nodes (for example after clustering). Now it takes into account only the nodes that are actually rendered solving the problems with sometimes huge empty spaces in hierarchies with clusters.
Also the Hierarchical Layout Methods example was modified to show clustering. It was actually mostly rewritten with new design, various code style improvements and more detailed info added atop of clustering.
PS: Merge #268 into this branch to make the errors go away.
- Closes #264.
=> fix(hierarchical): ignore invisible nodes

examples/network/basic_usage/peer.html
This now advises people to import files that actually exists and there's a little note added about version pinning on unpkg.com. It also includes `<div id="mynetwork"/>` as to make it explicit to people that it's necessary.
- Closes #278.
=> chore(examples): fix peer build example

cypress/integration/directed-hierarchical-layout.spec.ts, cypress/integration/helpers/common.ts, cypress/integration/helpers/index.ts, cypress/integration/helpers/trees.ts, cypress/pages/universal.html, cypress/support/access-globals.ts, cypress/support/commands.ts
This tests whether all nodes are placed and clickable (after stabilize and fit), the correct number of edges connects the visible nodes and that levels are evenly spaced without gaps. All forementioned is tested again before and after clustering. The test checks linear graphs, trees and general acyclic graphs. Some tests are also performed agains simple cyclic graphs but that's mostly to just make sure the layouting algorithm doesn't cycle forever or something like that.
This commit comes with universal HTML page that exposes it's variables for the spec file to use and commands that can take advantage of this. The idea here is to be able to execute any code from the spec file without having to create a new HTML for it. This was created as a side effect but in the end it is probably way …
=> test(e2e): add directed hierarchical layout test

.circleci/config.yml
The directory was simply not copied over there which lead to fancy Korean flags pointing nowhere.
=> ci(gh-pages): include Korean docs

examples/network/other/chosen.html
The labels in the [Chosen Elements example](https://visjs.github.io/vis-network/examples/network/other/chosen.html) do not change on hover as they're supposed to. Using the `ctx` param instead of `values` when editing the properties fixes the problem.
=> Fix labels in Chosen Elements example

lib/network/modules/Canvas.js
There was already a check for zero width and this adds the same check for height. The problem is that with zeroes this results in values such as infinity being computed and eventually leads to various things turning into NaN as subsequent calculations fail.
Closes #340.
=> fix(canvas): don't set camera state with zero height

lib/network/modules/View.js
It's perfectly valid for the canvas element to have zero size. However without any nodes that would lead to 0/0 and subsequent NaN zoom level.
This change makes it to simply set zoom level to 1 in such a case.
=> fix(view-fit): prevent potential NaN on zero sized canvas

lib/network/Network.js, lib/network/modules/Clustering.js
This contribution was cherry picked from @Menighin's (thanks by the way) PR to the original @almende/vis repository.
These methods are in the docs and declarations but in reality they don't exist. Since they're well documented they probably should exist otherwise people are forced to use `network.clustering` which is an internal module that people shouldn't access directly.
Closes #338.
=> fix(network): add missing clustering methods

lib/network/modules/NodesHandler.js
The label was updated only when the font or the label text itself changed but constraints affect it too so this triggers the update when they're changed.
Fixes #337.
=> fix(nodes): update labels on constraint change

lib/network/options.js, test/configure-options.test.ts
This wasn't documented before and many people made various mistakes in it. Some options were simply wrong so there are fixes for that. It also includes a test to prevent some common mistakes, like setting the step bigger than the range or initial value outside of the range, in the future.
=> fix(configurator): fix bugs and document the format

types/network/Network.d.ts
Fixes missing `imagePadding` property in `NodeOptions` definition.
=> add imagePadding to NodeOptions definition

docs/network/nodes.html
Hi,
Node ID is described as "String", but...
... almost all demo/examples I could see had numeric IDs
... some functionalities only work on fields having numeric values (see DataSet.max(), for instance).
-> so this pull request aims at describing node ID as "Number or String".
How modest it might be, this is my first contribution on github, hope I didn't miss a step ;-)
=> Node ID type ("String" -> "Number or String")

lib/network/modules/components/physics/HierarchicalRepulsionSolver.js
I have no idea why it was assigned in the first place. The new value was not used for anything at all.
Closes #555.
=> fix(hierarchical-repulsion-solver): remove assignment to const

lib/network/modules/components/Node.js
Node options are being overridden by the values defined by the Group, which should be the case, since more specific options (node) should have priority over more generic ones (group).
This [was fixed for `color`](https://github.com/almende/vis/issues/3713), but there are still many useful options such as borderWidth, image, and shape that are being overridden.
With this PR we fix this by not merging from the group any new option that has been set for the node.
Fix #408
=> Don't override Node options with Group options

examples/network/basic_usage/esnext.html, examples/network/basic_usage/peer.html, examples/network/basic_usage/standalone.html
We merged #526 but didn't update the examples. This fixes it.
Closes #588.
=> docs(builds): update outdated info and add missing ESNext

lib/network/modules/LayoutEngine.js
Hi,
This is a bug fix for when switching to hierarchical layout and backing up previous edge smooth options. The options were being backed up to `options.edges` instead of `options.edges.smooth`
I don't think this requires an example.
=> Fix incorrect backing up of edge smooth options

types/index.d.ts
The entry d.ts file for default export was missing, this creates it and therefore fixes errors when used in TS projects.
Closes #682.
Closes #649.
=> fix(types): add missing index file

lib/network/modules/InteractionHandler.js
Fixes https://github.com/visjs/vis-network/issues/709
This check ensures that the drag start event is not fired if already dragging. Fixes issue when more than 1 finger may be used on the screen to fire a drag. 
Tests ran fine, and basic examples testing also observed no new bugs.
=> Fix two fingers drag bug (#709)

renovate.json
I've been running after merging patches and minor dependencies from npm.
Thanks to renovate, this is does open PRs automatically but it does seem to spam versions and PRs which kinda sucks sometimes because they should be simply automatically merged in...
This PR will automatically merge them with no human interventions.
=> chore: automerge non-major dependencies versions

.circleci/config.yml, cypress/support/access-globals.ts
One of the examples renders massive network which often exceeds the default timeout even though it works as intended. Also the stabilization in E2E often exceeds its timeout.
=> ci: increase timeouts

README.md
We use Renovate for quite some time now. I also added a dependency state from https://david-dm.org/.
=> chore(readme): replace Greenkeeper badge

.gitignore, docs-kr/network/nodes.html, docs/network/nodes.html, examples/network/nodeStyles/imagesWithCoordinateOrigin.html, lib/network/modules/NodesHandler.js, lib/network/modules/components/Node.js, lib/network/modules/components/nodes/shapes/CircularImage.js, lib/network/modules/components/nodes/shapes/Image.js, lib/network/options.js, types/network/Network.d.ts
This PR allows the use of (x, y) of the node as the (0, 0) position of the image instead of using width/2 and height/2.
A new shape property was added: coordinateOrigin (default 'center'). The new option `top-left` allows the image/circle image's top-left corner to be the x,y position of the node
Closes https://github.com/visjs/vis-network/issues/811
Closes https://github.com/visjs/vis-network/pull/812
=> New coordinateOrigin prop to change image/circularImage positioning

.circleci/config.yml
I accidentally deleted a command from CircleCI config in #858, this fixes it.
Closes #876.
=> ci: generate examples

cypress/integration/visual/z-index.spec.ts
Just a simple snapshot of rendering order to provide early warning about issues like #883.
=> test(z-index): test node/edge/arrow/label Z axis rendering order

cypress/integration/visual/z-index.spec.ts, cypress/support/commands/vis-simple-canvas-snapshot.ts, lib/network/modules/CanvasRenderer.js, lib/network/modules/components/Node.js, lib/network/modules/components/nodes/shapes/Diamond.js, lib/network/modules/components/nodes/shapes/Dot.js, lib/network/modules/components/nodes/shapes/Hexagon.js, lib/network/modules/components/nodes/shapes/Icon.js, lib/network/modules/components/nodes/shapes/Square.js, lib/network/modules/components/nodes/shapes/Star.js, lib/network/modules/components/nodes/shapes/Triangle.js, lib/network/modules/components/nodes/shapes/TriangleDown.js, lib/network/modules/components/nodes/util/ShapeBase.js
This places external node labels (labels outside of the node's shape) above arrows. This is how it was before #761 (the reason is that the arrows can pierce into nodes and therefore have to be above the nodes). The way this works is that the draw function returns label drawing function and the renderer invokes the label drawing function later to draw over the arrows.
The E2E test has also been extended to test all the shapes instead of just two.
Partially solves #883 (custom shape still has to be addressed).
=> fix(rendering): render external node labels above arrows

cypress/integration/visual/z-index.spec.ts, cypress/pages/standard-cytest-script.ts, docs/network/nodes.html, lib/network/modules/components/nodes/shapes/CustomShape.js, lib/network/modules/components/nodes/util/ShapeBase.js
Basically the same as #932, it allows people to return an object (more props can be added without breaking changes or old props can receive special treatment to keep backwards compatibility) render something bellow/before arrows (`drawNode`) or above/after them (`drawExternalLabel`), the names are based on the primary purpose of those functions, though they can be used in any way that works of course. The rendering in the function itself will work as before so no breaking changes here.
Closes #883.
PS: The Z index visual regression test was extended to test the custom shape.
=> feat(node-custom-shape): return draw function for different layers 

cypress/integration/visual/cluster-and-open.spec.ts
It's as simple as that, cluster nodes, open the cluster and take a screenshot of each step.
=> test(cluster): visual E2E of opening and closing with different release functions

lib/module/hammer.js
The CJS version causes problems with upcomming CommonJS Rollup plugin update.
=> refactor(hammer): rewrite into ESM

cypress/integration/visual/layout-hierarchical-directed-levels.spec.ts, cypress/support/commands/index.ts, cypress/support/commands/vis-simple-canvas-snapshot.ts, cypress/support/commands/vis-snapshot-opened-page.ts, lib/network/modules/LayoutEngine.js, lib/network/modules/layout-engine/index.ts
The infinite cycle prevention used to cut off when there were multiple one way paths between nodes, this is fixed now. Leftover levels from previous runs are also now cleared (I'm not sure if it caused any issues as all the visible node levels were always overwritten but it was definitely a little memory leak for people adding and removing nodes without reusing ids, not a good thing either way).
Includes visual regression test.
Closes #956.
=> fix(layout): directed hierarchical for acyclic graphs

docs/network/nodes.html, examples/network/nodeStyles/shapes.html, lib/network/modules/components/nodes/shapes/CustomShape.js
Add node id to the custom ctx renderer function's arguments so that users can distinguish individual nodes.
Closes #979.
=> feat(node-ctx-renderer): add node id

cypress/integration/visual/initial-positioning.no-fixed-no-positions.json, cypress/integration/visual/initial-positioning.no-fixed-some-positions.json, cypress/integration/visual/initial-positioning.some-fixed-some-positions.json, cypress/integration/visual/initial-positioning.spec.ts, lib/network/modules/KamadaKawai.js
Kamada Kawai used to reposition fixed nodes, however fixed nodes should not move at all.
This PR fixes that and also includes visual regression test.
Closes #991.
=> fix(kamada-kawai): don't reposition fixed nodes

examples/network/other/automaticResizing.html, lib/network/modules/Canvas.js
This removes the delay after container element dimensions are changed and before the canvas pixel dimensions are changed.
Doesn't work in IE11, the old behavior is retained there.
Closes #1011.
=> perf(resizing): use ResizeObserver if available

docs/network/nodes.html
The docs contained unclear and untrue statements.
Closes #1027.
=> docs(node): rewrite x and y position descriptions

package-lock.json, package.json
It has to be a dependency as we invoke it in postinstall, dev
dependencies are ignored by install. If it's just dev dependency, it
only produces an error message and there isn't really much of a point in
having it at all.
Closes #1083.
=> chore(deps): make OpenCollective runtime dep

lib/network/modules/EdgesHandler.js, lib/network/modules/NodesHandler.js
This tests that the methods and properties are implemented instead of checking the prototype. Thanks to this it is now possible to use a different DataSet or DataView without extending the Vis one. This also removes some interoperability issues of the standalone build when used toghether with other Vis family libraries.
=> feat(data): allow custom DataSet/View implementations

lib/shared/Configurator.js, test/Network.test.js
Array.isArray works with arrays that came from other contexts like web workers, instanceof Array wouldn't consider such array to be an array even though it is perfectly valid array.
=> fix: purge instanceof Array from the codebase

cypress/integration/visual/selection.spec.ts, lib/network/modules/SelectionHandler.js
This was introduced by #1133, it was a simple matter of forgetting to commit the selection after making changes to it which resulted in the nodes not being highlighted as they should be. A visual regression test is included to test that the selection is rendered properly.
Closes #1135.
=> fix(selection): highlight selected nodes when set programatically

lib/network/Network.js, lib/network/modules/Groups.js
Deduping group names saves negligible amount of memory and makes all groups equally likely to be selected as new group templates.
Regardings refactoring, properties not accessed from the outside were renamed with leading underscore to mark them as private. Default export was converted to named export. Map is used instead of object for key (name) value (style) storage of groups.
Closes #1170.
=> fix(groups): dedupe group names (+ some refactoring)

docs/network/index.html
Hi !
Just a small correction of an error in the documentation for importing data from a JSON Gephi.
Before:
After:
=> Fix typo in docs code (Importing data from Gephi)

cypress/integration/visual/selection.spec.ts, lib/network/modules/SelectionHandler.js, test/helpers/index.ts, test/network/selection.test.js, types/network/Network.d.ts
This is how it was before #1138, includes some tests (visual and unit) and a related small fix in types.
Closes #1198.
=> fix(selection): commit selection changes in unselectAll

cypress/pages/standard-cytest-script.ts
Given the types this did absolutely nothing, the only case when it would do something (i.e. convert `string | number` to `[string | number]`) would be reported by TS as an error if used.
=> refactor(cypress): remove redundant code

lib/shared/Activator.js
This is mostly just to make it easier to move this into Vis Util. I especially wanted to get rid of Keycharm as it's used solely to (un)bind escape key listener and has basically zero added value in this code. This wouldn't really be a problem otherwise as Keycharm is also used elsewhere but it's not a dependency of Vis Util and for this single task it seems dumb to include it in Vis Util.
Remove the dependency on Keycharm: All it really did was translate `"esc"` to `event.keyCode === 27` (which is deprecated by the way). We can just use `"key" in event ? event.key === "Escape" : event.keyCode === 27` instead of Keycharm and not rely solely on deprecated APIs.
Remove the use of `addClassName` and `removeClassName`: These basically polyfill IE9 and it's contemporaries (this is Windows …
=> refactor(activator): various changes

cypress/pages/pollution.html, docs-kr/network/index.html, docs/network/index.html, examples/network/data/dynamicData.html, examples/network/data/importingFromGephi.html, examples/network/edgeStyles/arrowTypes.html, examples/network/events/interactionEvents.html, examples/network/events/physicsEvents.html, examples/network/exampleApplications/loadingBar.html, examples/network/labels/labelAlignment.html, examples/network/layout/hierarchicalLayout.html, examples/network/layout/hierarchicalLayoutOverlapAvoidance.html, examples/network/layout/hierarchicalLayoutUserdefined.html, examples/network/other/animationShowcase.html, examples/network/other/changingClusteredEdgesNodes.html, examples/network/other/manipulation.html, examples/network/other/manipulationEditEdgeNoDrag.html, examples/network/other/navigation.html, examples/network/other/performance.html, lib/network/modules/Canvas.js, lib/network/modules/ManipulationSystem.js, lib/shared/ColorPicker.js, lib/shared/Configurator.js, lib/shared/Popup.js
We had a lot of instances of innerHTML that were simply setting text, in quite a few cases parsing it as HTML was even counter productive as it could theoretically result in syntax errors and corrupted output (e.g. the output of JSON.stringify definitely shouldn't be parsed as HTML).
There is only one occurrence of innerHTML left and that is for the node/edge title as the docs clearly state that any string passed will be parsed as HTML.
=> fix(xss): don't use innerHTML to set plain text or wrap text into an element

cypress/integration/visual/selection.spec.ts, cypress/pages/standard-cytest-script.ts, cypress/support/commands/index.ts, cypress/support/commands/types.ts, cypress/support/commands/vis-assert-event.ts, cypress/support/commands/vis-run.ts, lib/network/Network.js, lib/network/modules/SelectionHandler.js, test/network/selection.test.js
Deselect events are fired again as they should after user interactions that caused something to be deselected.
There are also some tests and assertions included, this is actually most of the changes. The assertions work with any event in E2E tests, not only selection events, though only selection events are used in tests at the moment.
Closes #1277, closes #1264.
=> fix(selection): deselect events not being fired

docs/network/edges.html, docs/network/nodes.html, examples/network/other/html-in-titles.html
Clarify how to use HTML in titles as some people were confused by the stale docs (from before we switched to innerText due to XSS) and didn't realise it was simple to get the old behavior back.
=> chore(docs): update HTML in titles references and add an example

lib/network/modules/InteractionHandler.js
It was changed but not committed with lead to issues like sometimes the wrong node being moved when dragging.
The `unselectAll` and `selectObject` methods modify the selection but don't commit the selection which is necessary to rerender etc. The `setSelection` method replaces the selection and commits it automatically. This way when an unselected node is dragged it will be selected as the code suggest it should and as it is when the selection is empty.
Closes #1596.
Closes #1599 - This is a workaround that resets the selection to the state before drag to hide #1596, it doesn't solve the issue though, it just hides it.
=> fix(interaction-handler): commit selection change on drag start

docs/network/index.html
Changed "sepparately" to "separately" in the "getting started" section
=> Fix typo in index.html

lib/network/modules/InteractionHandler.js
When shift was pressed and the drag started on a node both were initialized. Afterwards dragging moved the node and drag end finished the selection leaving the node fixed and unable to be dragged again.
Closes #1540.
=> fix(interaction): initialize selection or dragging/paning but never both

docs/network/layout.html
The documentation seemed to have a simple mistake, where `leaves` is the default parameter rather than `roots`.
=> Fix typo in layout.html documentation

lib/network/modules/LayoutEngine.js, lib/network/modules/components/DirectionStrategy.js, package-lock.json, package.json, rollup.build.js
Up to the ECMAScript standard `Array.sort` is stable and all the browsers that we polyfill already implement it that way so we don't need timsort anymore.
=> fix(deps): remove timsort

lib/network/modules/components/DirectionStrategy.js
`.sort()` was missing in HorizontalStrategy in #1946
=> fix(horizontal-strategy): add missing sort method

lib/network/modules/Canvas.js
These are polyfills for very old browsers. We don't polyfill these browsers using core-js (i.e. it most likely doesn't work in them anyway) and barely anyone is using them nowadays.
=> perf: remove add/remove event listener polyfills

cypress.config.ts, cypress/plugins/index.ts, cypress/tsconfig.json
It's not necessary anymore, Cypress works just fine with TS files now. The transpilation is kept for files that are loaded from served HTML files though as that has to be transpiled manually.
=> chore(cypress): remove some custom transpilation

lib/network/modules/CanvasRenderer.js, test/canvas-mock.js
This served unsupported browsers (IE 9 era, no longer supported) and our test setup without proper polyfills for necessary browser APIs.
I mostly need to remove this because without it I can't merge all of the updates that are still pending across Vis.js repos. With updated dependencies it fails on maximum call stack size exceeded. Though it also cuts down on bundle size and reduces overhead.
=> perf(canvas-renderer): remove requestAnimationFrame polyfill/compat

lib/entry-esnext.ts, lib/index-legacy.ts, lib/network/Network.js, lib/network/modules/ManipulationSystem.js, lib/network/modules/components/NavigationHandler.js
Tests run in Node without CSS support. The style imports were ignored anyway. Not importing CSS into tests in the first place will make things easier, especially transition to ESM where require won't work.
=> refactor(styles): remove CSS from tests
