visjs/vis-network

.gitignore
package-lock.json
package.json

Pretty self explaining.
Fixes: #2.

Update vis-data and commit package-lock

---

lib/network/locales.js

This pull request was originally by @scenaristeur
https://github.com/almende/vis/pull/3963
it also was adopted in 
https://github.com/visjs-community/visjs-network/pull/20

vis#3963: add French

---

lib/network/modules/Clustering.js

This is an original contribution from @Tyler-Maclachlan: https://github.com/visjs-community/visjs-network/pull/71
part of #7

visjs-network#71: fix remove edge from clustering

---

.circleci/config.yml
.releaserc.yml
package-lock.json
package.json

Installs, tests, builds and releases (semantic-release) if necessary.
Linting is commented out at the moment (too many failures). It should be uncommented later when the code base is compliant.
Addresses #1.
PS @mojoaxel: I can't set this (or any other repo) up on CircleCI. It says: “You must be an admin to add a project on CircleCI”.

chore(CI): add CircleCI config

---

test/edges/helpers.ts

docs: add missing doc comment

---

package-lock.json
package.json

fix(package): update vis-util to version 1.1.6

---

lib/network/modules/components/Edge.js
test/edge-color.test.ts

fix: edge color not changing

---

docs/network/edges.html
docs/network/index.html
types/network/Network.d.ts

chore(docs): update outdated (broken) links

---

package-lock.json
package.json

I just couldn't find any reference to any of them and nothing is broken without them.

chore(deps): remove unused dependencies

---

examples/network/exampleUtil.js

This greatly reduces differences between examples' screenshots after they've been regenerated. This is a complement to the fixed layout seed included in #140.

Deterministic example util

---

.github/PULL_REQUEST_TEMPLATE.md

A few people has been confused by this already.

chore(github): replace develop branch with master

---

docs/network/physics.html
examples/network/layout/hierarchicalLayoutOverlapAvoidance.html
lib/network/modules/components/physics/HierarchicalRepulsionSolver.js
lib/network/options.js

The same thing as in Barnes Hut.
Includes an example and docs.
Live example: https://jsfiddle.net/thomaash/cmaojfg2/.
Closes #168.

feat(hierarchical-layout): add avoid overlap

---

lib/network/modules/Canvas.js
lib/network/modules/InteractionHandler.js

I messed up my fork for PR #170, so I created a new fork and created a new PR.
@Thomaash I see what you meant, I have changed my code accordingly, it should be much cleaner now. :+1:

Fix scroll event listener to new standard

---

cypress/fixtures/example.json
cypress/plugins/index.js

These files are useless example files but Cypress keeps creating them so let's commit them into the repo to make Cypress happy that it has these stub config files.

chore(cypress): commit stub files

---

docs/network/edges.html

hi, I'm university student of Korea. :)
I find **three typing mistakes** that is wrong to me.
I want you to make sure it's a good discovery.
Thank you!
**Thank you for contributing to vis.js!!**
- Closes #251.

docs(edges): fix some typos

---

docs/network/index.html

chore(docs): fix typo

---

.circleci/config.yml

This will resolve the styling issues we currently have.

docs: publish missing files on GH Pages

---

cypress/integration/clicks.spec.ts
cypress/integration/drags.spec.ts
cypress/integration/helpers/common.ts
cypress/pages/events-target.html

This tests clicks and dragging:
- That they don't fire outside of canvas.
- That they do fire inside of canvas.
- That they have correct DOM coords.
- That they're canvas coords have the expected relative distances.

test(e2e): add click and drag tests

---

README.md

docs(readme): fix example chart image link

---

docs-kr/network/physics.html
docs/network/physics.html
lib/network/options.js

I have no idea why this was disabled. There are no comments explaining it and blame was also unhelpful. Hopefully someone just messed up adding theta.
Closes #415.

fix(physics): allow theta to be configured

---

lib/network/modules/Clustering.js
lib/network/modules/ManipulationSystem.js
package-lock.json
package.json
rollup.build.js
rollup.config.js

This also updates Vis Util to version 3 as these two things have to be done in the same PR.

fix(uuid): replace vis-uuid by uuid

---

cypress/integration/manipulation.spec.ts
cypress/pages/simple.html
cypress/support/commands.ts

This tests a bit more of the manipulation functionality (edits and deletes).

e2e: improve manipulation

---

common-docs-files/css/style.css
common-docs-files/img/flags/zh.svg
docs-kr/network/configure.html
docs-kr/network/edges.html
docs-kr/network/groups.html
docs-kr/network/index.html
docs-kr/network/interaction.html
docs-kr/network/layout.html
docs-kr/network/manipulation.html
docs-kr/network/nodes.html
docs-kr/network/physics.html
docs/network/configure.html
docs/network/edges.html
docs/network/groups.html
docs/network/index.html
docs/network/interaction.html
docs/network/layout.html
docs/network/manipulation.html
docs/network/nodes.html
docs/network/physics.html
index.html

@aimeiyijia maintains Chinese translation of our docs on their website. This PR adds links to it besides the already existing links to en/kr translations. There is a note next to the link about this translation being third party as it's on a completely different domain that is not under our control.
Closes #778.

docs(i18n): add links to Chinese docs

---

docs-kr/network/configure.html
docs-kr/network/edges.html
docs-kr/network/groups.html
docs-kr/network/index.html
docs-kr/network/interaction.html
docs-kr/network/layout.html
docs-kr/network/manipulation.html
docs-kr/network/nodes.html
docs-kr/network/physics.html
docs/network/configure.html
docs/network/edges.html
docs/network/groups.html
docs/network/index.html
docs/network/interaction.html
docs/network/layout.html
docs/network/manipulation.html
docs/network/nodes.html
docs/network/physics.html
index.html

Link to Chinese translation over HTTPS since it's now available.
Closes #799.

docs(zh): switch to HTTPS

---

docs/network/nodes.html
lib/network/modules/components/nodes/util/ShapeBase.js

Revert "fix: add label prop to ctxRenderer"

---

docs/network/nodes.html
lib/network/modules/components/nodes/util/ShapeBase.js

Revert "Revert "fix: add label prop to ctxRenderer""

---

docs-kr/network/interaction.html
docs/network/interaction.html

This has been implemented for years and is even validated by the validator.
Closes #1018.

docs: add options.interaction.zoomSpeed

---

types/network/Network.d.ts

Transferring from PR to DefinitelyTyped
+ Update type definitions for NetworkEvents
+ Updates type definitions for EdgeOptions
+ Refactors Font and ArrowHead typings to reduce repeated types
closes #1093

Updating Types from Documentation

---

cypress/integration/visual/node-shapes.spec.ts
lib/network/modules/NodesHandler.js
lib/network/modules/components/Node.js

Border width selected was mostly ignored in code even though it's in the docs. This PR aligns the implementation with the docs and also includes visual regression test.
Closes #1142.

fix(node-border): use borderWidthSelected when set

---

lib/network/dotparser.js

Optimized isAlphaNumeric to use charcodes instead if regex. This gives the function a worst case 60%+ performance on V8 and 40%+ on Spidermonkey

Optimized isAlphaNumeric

---

types/network/Network.d.ts

fix Node.title type

---

types/network/Network.d.ts

Fixed Edge.title type (#1382)

---

.circleci/config.yml

Small without browsers where that's enough bigger with browsers where it's actually needed.

ci(docker): use more approriate imgs

---

docs/network/index.html

**Thank you for contributing to vis.js!!**
Please make sure to check the following requirements before creating a pull request:

fixed typo

---

docs/network/index.html

I looked online and 'focused' seems to be the preferred spelling, 'focussed' is the older spelling.

fix some typos

---

docs/network/edges.html
docs/network/nodes.html

Fix doc typos

---

.circleci/config.yml

2G of RAM just doesn't seem to be enough anymore.

ci: increase resource class

---

docs-kr/network/configure.html
docs-kr/network/edges.html
docs-kr/network/groups.html
docs-kr/network/index.html
docs-kr/network/interaction.html
docs-kr/network/layout.html
docs-kr/network/manipulation.html
docs-kr/network/nodes.html
docs-kr/network/physics.html
docs/network/configure.html
docs/network/edges.html
docs/network/groups.html
docs/network/index.html
docs/network/interaction.html
docs/network/layout.html
docs/network/manipulation.html
docs/network/nodes.html
docs/network/physics.html

This lib is dead, haven't been updated in a long time and I couldn't even find anything in our docs that would scroll smoothly.

docs(deps): remove smooth scroll
